#
# Continuous integration config
# http://travis-ci.org/aduros/flambe

language: node_js
node_js: ["0.8", "0.10"]
env:
    global:
        - secure: "gIXPIfKJcPgQxR/1YuT3RzNjoJCPRK7gsck9Z0IeyRoQH0PVblbov8K49wz8\nMsV7GpUbLhD8p/V4MbKCodhrC+rZUjr/zPnu6KHg+B6tkOk1bc2YKqrK5q7b\n4BBKgSSJS0jHudzzWAPfDDhPbnjRaBnrlONgVMVk5BS//g1KIbc="

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib

script: bin/run-travis
