#!/usr/bin/env python

from waflib import *

# Setup options for display when running waf --help
def options(ctx):
    ctx.load("haxe", tooldir="../tools")

# Setup configuration when running waf configure
def configure(ctx):
    ctx.load("haxe", tooldir="../tools")
    ctx.find_program("node", var="NODE")

# Runs the build!
def build(ctx):
    ctx(features="haxe",
        classpath = [ ctx.path.find_dir("src"), ctx.path.find_dir("../src") ],
        target="runner.js",
        flags="-main TestMain -D server")

    ctx(rule="${NODE} ${SRC}", source="runner.js", always=True)
