#!/bin/sh
#
# Builds the FlashDevelop plugin

set -e

PLUGIN_ROOT=`readlink -f $(dirname $0)`
cd "$PLUGIN_ROOT"

BASE_DIR='$(BaseDir)/Projects/380 HaXe - Flambe Project'

# Sanity check
if [ ! -d "$BASE_DIR" ]; then
    echo "Could not find directory: $BASE_DIR"
    exit 1
fi

FDZ="flambe-FlashDevelop.fdz"
rm -f "$FDZ"
git ls-files '$(BaseDir)' | zip "$FDZ" -@

# Include an empty assets directory, since git can't handle empty dirs
ASSET_DIR="$BASE_DIR/assets/bootstrap"
mkdir -p "$ASSET_DIR"
zip "$FDZ" "$ASSET_DIR"
