#!/usr/bin/env python

from waflib import *

# Setup options for display when running waf --help
def options(ctx):
    ctx.load("haxe", tooldir="../tools")

# Setup configuration when running waf configure
def configure(ctx):
    ctx.load("haxe", tooldir="../tools")
    ctx.find_program("node", var="NODE")

# Runs the build!
def build(ctx):
    ctx(features="haxe",
        classpath = [ ctx.path.find_dir("src"), ctx.path.find_dir("../src") ],
        target="run.n",
        flags="-main FlambeMain")

# Helper command to build the .n and test the "new" command
# Run it with `wafl test`
def test(ctx):
    Scripting.run_command("build")
    import os
    os.execlp("neko", "neko", "build/run.n", "new", "/tmp")
