#!/usr/bin/env python

FLAMBE_DIR = "../.."

def options(ctx):
    ctx.load("flambe", tooldir=FLAMBE_DIR+"/tools")

def configure(ctx):
    ctx.load("flambe", tooldir=FLAMBE_DIR+"/tools")

def build(ctx):
    platforms = ["flash", "html"]
    if ctx.env.has_android:
        platforms += ["android"]

    ctx(features="flambe",
        platforms=platforms,
        airPassword="samplePassword",
        main="shooter.Main")
